import { join } from 'node:path';

import { expect, test, type Page } from '@playwright/test';

import { gotoTool } from './helpers';

/**
 * Image tool journeys (spec §10.5 item 4, §10.4 file fixtures).
 *
 * Every fixture is generated by tests/fixtures/generate.mjs and contains no
 * personal data.
 */

const FIXTURES = join(process.cwd(), 'tests/fixtures/images');
const fixture = (name: string) => join(FIXTURES, name);

async function addFiles(page: Page, ...names: string[]) {
  await page.locator('input[type="file"]').setInputFiles(names.map(fixture));
}

/**
 * Scopes a query to the interactive panel.
 *
 * Every tool page also carries editorial content that legitimately repeats the
 * same phrases — "Stretch distorts the image", "64 × 32 pixels" — so an
 * unscoped query is ambiguous and can pass against prose rather than the tool.
 */
function tool(page: Page, name: string) {
  return page.getByRole('region', { name: `${name} tool` });
}

/** The batch summary, named to distinguish it from slider <output> elements. */
function summary(page: Page) {
  return page.getByRole('status', { name: 'Batch summary' });
}

test.describe('image compressor', () => {
  test('processes a batch and reports before and after sizes', async ({ page }) => {
    await gotoTool(page, '/tools/image-compressor');

    const panel = tool(page, 'Image Compressor');
    await addFiles(page, 'gradient-64x32.png', 'wide-100x20.png');
    await expect(panel.getByText('2 files')).toBeVisible();

    await page.getByRole('button', { name: 'Compress images' }).click();

    await expect(summary(page)).toContainText('2 of 2 processed', { timeout: 20_000 });
    // Dimensions are reported per file.
    await expect(panel.getByText('64 × 32').first()).toBeVisible();
  });

  test('offers a ZIP once two or more files succeed', async ({ page }) => {
    await gotoTool(page, '/tools/image-compressor');
    await addFiles(page, 'gradient-64x32.png', 'wide-100x20.png');
    await page.getByRole('button', { name: 'Compress images' }).click();
    await expect(summary(page)).toContainText('2 of 2 processed', { timeout: 20_000 });

    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download all as ZIP' }).click();
    const download = await downloadPromise;
    expect(download.suggestedFilename()).toBe('compressed-images.zip');
  });

  test('downloads a single processed file with the right extension', async ({ page }) => {
    await gotoTool(page, '/tools/image-compressor');
    await addFiles(page, 'gradient-64x32.png');

    await page.getByLabel('Output format').selectOption('image/jpeg');
    await page.getByRole('button', { name: 'Compress images' }).click();
    await expect(summary(page)).toContainText('1 of 1 processed', { timeout: 20_000 });

    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download', exact: false }).last().click();
    const download = await downloadPromise;
    expect(download.suggestedFilename()).toMatch(/\.jpg$/);
  });

  test('reports honestly when the output is larger', async ({ page }) => {
    await gotoTool(page, '/tools/image-compressor');
    // A tiny flat PNG re-encoded as PNG has nowhere to shrink to.
    await addFiles(page, 'wide-100x20.png');
    await page.getByRole('button', { name: 'Compress images' }).click();
    await expect(summary(page)).toContainText('1 of 1 processed', { timeout: 20_000 });

    // Either outcome is acceptable; what matters is that it is stated.
    await expect(summary(page)).toContainText(/smaller|larger|no change/);
  });
});

test.describe('file validation', () => {
  test('refuses a file that is not an image, naming what it accepts', async ({ page }) => {
    await gotoTool(page, '/tools/image-compressor');
    await addFiles(page, 'not-an-image.txt');

    const rejection = tool(page, 'Image Compressor').getByRole('alert');
    await expect(rejection).toContainText(/not in a format this tool recognises/i);
    await expect(rejection).toContainText('JPG, PNG and WebP');
  });

  test('refuses a PNG on the JPG-only compressor and says which format it is', async ({ page }) => {
    await gotoTool(page, '/tools/jpg-compressor');
    await addFiles(page, 'gradient-64x32.png');

    const rejection = tool(page, 'JPG Compressor').getByRole('alert');
    await expect(rejection).toContainText('PNG');
    await expect(rejection).toContainText('JPG and JPEG only');
  });

  test('fails cleanly on a corrupt file rather than freezing', async ({ page }) => {
    await gotoTool(page, '/tools/png-compressor');
    await addFiles(page, 'corrupt.png');

    // Sniffing passes (valid PNG signature) so it enters the queue, then the
    // decode fails with a message rather than hanging.
    await page.getByRole('button', { name: 'Compress PNGs' }).click();
    await expect(
      tool(page, 'PNG Compressor').getByText(/could not be read as an image/i),
    ).toBeVisible({ timeout: 20_000 });

    // The page is still responsive.
    await expect(page.getByRole('button', { name: 'Compress PNGs' })).toBeEnabled();
  });

  test('removing one file leaves the rest of the queue intact', async ({ page }) => {
    await gotoTool(page, '/tools/image-compressor');
    const panel = tool(page, 'Image Compressor');
    await addFiles(page, 'gradient-64x32.png', 'wide-100x20.png', 'tall-20x100.png');
    await expect(panel.getByText('3 files')).toBeVisible();

    await page.getByRole('button', { name: /Remove wide-100x20\.png/ }).click();
    await expect(panel.getByText('2 files')).toBeVisible();

    // Scoped to the row titles: each filename also appears in its Remove
    // button's screen-reader label, so an unscoped text query is ambiguous.
    const rows = panel.locator('li p.truncate');
    await expect(rows).toHaveText(['gradient-64x32.png', 'tall-20x100.png']);
  });
});

test.describe('format conversion', () => {
  test('JPG to PNG produces a PNG and explains the size increase', async ({ page }) => {
    await gotoTool(page, '/tools/jpg-to-png');
    await addFiles(page, 'plain.jpg');

    await expect(
      tool(page, 'JPG to PNG Converter').getByText(/several times larger/i),
    ).toBeVisible();

    await page.getByRole('button', { name: 'Convert to PNG' }).click();
    await expect(summary(page)).toContainText('1 of 1 processed', { timeout: 20_000 });

    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download', exact: false }).last().click();
    expect((await downloadPromise).suggestedFilename()).toMatch(/\.png$/);
  });

  test('PNG to JPG exposes the matte colour and warns transparency is lost', async ({ page }) => {
    await gotoTool(page, '/tools/png-to-jpg');
    await addFiles(page, 'transparent-32x32.png');

    await expect(
      tool(page, 'PNG to JPG Converter').getByText(/Transparency is removed/i),
    ).toBeVisible();
    await expect(page.getByLabel('Background for transparent areas')).toBeVisible();

    await page.getByRole('button', { name: 'Convert to JPG' }).click();
    await expect(summary(page)).toContainText('1 of 1 processed', { timeout: 20_000 });
  });

  test('PNG compressor states that the lossless pass may save nothing', async ({ page }) => {
    await gotoTool(page, '/tools/png-compressor');
    await addFiles(page, 'gradient-64x32.png');
    await expect(tool(page, 'PNG Compressor').getByText(/sometimes zero/i)).toBeVisible();
  });
});

test.describe('image resizer', () => {
  test('derives the second dimension with the aspect locked', async ({ page }) => {
    await gotoTool(page, '/tools/image-resizer');
    await addFiles(page, 'gradient-64x32.png');

    // The source size appears both in the file summary and in the predicted
    // output, so assert on the file summary explicitly.
    await expect(
      tool(page, 'Image Resizer').getByText('64 × 32 pixels', { exact: false }).first(),
    ).toBeVisible();

    await page.getByLabel('Width').fill('32');
    // 64×32 is 2:1, so a width of 32 gives a height of 16.
    await expect(page.getByLabel('Height')).toHaveValue('16');

    await expect(page.getByRole('region', { name: 'Resize result' })).toContainText('32 × 16');
  });

  test('resizes and downloads', async ({ page }) => {
    await gotoTool(page, '/tools/image-resizer');
    await addFiles(page, 'gradient-64x32.png');

    await page.getByLabel('Width').fill('32');
    await page.getByRole('button', { name: 'Resize image' }).click();

    const result = page.getByRole('region', { name: 'Resize result' });
    await expect(result).toContainText('32 × 16', { timeout: 20_000 });

    const downloadPromise = page.waitForEvent('download');
    await result.getByRole('button', { name: /Download/ }).click();
    expect((await downloadPromise).suggestedFilename()).toMatch(/\.png$/);
  });

  test('does not enlarge unless asked', async ({ page }) => {
    await gotoTool(page, '/tools/image-resizer');
    await addFiles(page, 'gradient-64x32.png');

    await page.getByLabel('Width').fill('500');
    // Clamped back to the source size.
    await expect(page.getByRole('region', { name: 'Resize result' })).toContainText('64 × 32');

    await page.getByLabel('Allow enlarging').check();
    await expect(page.getByRole('region', { name: 'Resize result' })).toContainText('500 × 250');
  });

  test('warns that stretch distorts', async ({ page }) => {
    await gotoTool(page, '/tools/image-resizer');
    await addFiles(page, 'gradient-64x32.png');

    await page.getByLabel('Lock aspect ratio').uncheck();
    await page.getByRole('radio', { name: 'Stretch' }).check();
    await expect(
      tool(page, 'Image Resizer').getByText(/Stretch distorts the image/i),
    ).toBeVisible();
  });
});

test.describe('image cropper', () => {
  test('exports at source resolution, not preview resolution', async ({ page }) => {
    await gotoTool(page, '/tools/image-cropper');
    await addFiles(page, 'gradient-64x32.png');

    await page.getByLabel('Crop width').fill('40');
    await page.getByLabel('Crop height').fill('20');

    const result = page.getByRole('region', { name: 'Crop result' });
    await expect(result).toContainText('40 × 20');
    await expect(result).toContainText(/full source resolution/i);

    await page.getByRole('button', { name: 'Crop image' }).click();
    await expect(result).toContainText('40 × 20', { timeout: 20_000 });
  });

  test('keeps the crop inside the image', async ({ page }) => {
    await gotoTool(page, '/tools/image-cropper');
    await addFiles(page, 'gradient-64x32.png');

    // Far beyond the 64 × 32 source.
    await page.getByLabel('Crop width').fill('9999');
    await expect(page.getByLabel('Crop width')).toHaveValue('64');

    await page.getByLabel('X', { exact: true }).fill('9999');
    await expect(page.getByLabel('X', { exact: true })).toHaveValue('0');
  });

  test('is operable with the keyboard', async ({ page }) => {
    await gotoTool(page, '/tools/image-cropper');
    await addFiles(page, 'gradient-64x32.png');

    await page.getByLabel('Crop width').fill('20');
    await page.getByLabel('Crop height').fill('10');
    await page.getByLabel('X', { exact: true }).fill('10');

    const cropArea = page.getByRole('application', { name: /Crop area/ });
    await cropArea.focus();
    await expect(cropArea).toBeFocused();

    await page.keyboard.press('ArrowRight');
    await expect(page.getByLabel('X', { exact: true })).toHaveValue('11');

    await page.keyboard.press('Shift+ArrowRight');
    await expect(page.getByLabel('X', { exact: true })).toHaveValue('21');
  });

  test('applies an aspect preset', async ({ page }) => {
    await gotoTool(page, '/tools/image-cropper');
    await addFiles(page, 'gradient-64x32.png');

    await page.getByLabel('Aspect ratio').selectOption('1:1');
    // The largest square in a 64 × 32 image is 32 × 32.
    await expect(page.getByLabel('Crop width')).toHaveValue('32');
    await expect(page.getByLabel('Crop height')).toHaveValue('32');
  });
});

test.describe('privacy', () => {
  test('no image bytes are sent anywhere', async ({ page }) => {
    const suspicious: string[] = [];

    page.on('request', (request) => {
      const post = request.postData();
      if (post && post.length > 500) {
        suspicious.push(`${request.method()} ${request.url()} (${post.length} bytes)`);
      }
      if (/upload|convert|process/i.test(new URL(request.url()).pathname)) {
        suspicious.push(`suspicious path: ${request.url()}`);
      }
    });

    await gotoTool(page, '/tools/image-compressor');
    await addFiles(page, 'gradient-64x32.png', 'transparent-32x32.png');
    await page.getByRole('button', { name: 'Compress images' }).click();
    await expect(summary(page)).toContainText('2 of 2 processed', { timeout: 20_000 });

    expect(suspicious, 'image data may have left the device').toEqual([]);
  });
});
