import type { ToolDefinition } from './types';

/**
 * The 30 launch tools (spec §4). Exactly one entry per canonical route.
 *
 * Adding a tool means adding an entry here, a content module under
 * `content/tools/` and a component in the lazy map. The invariants in
 * `lib/registry/validate.ts` fail the build if any of the three is missing.
 */
export const tools: readonly ToolDefinition[] = [
  // --- Calculators (1–9) ---------------------------------------------------
  {
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    shortName: 'Percentage',
    category: 'calculators',
    title: 'Free Percentage Calculator — Show the Steps',
    description:
      'Work out a percentage of a number, what percentage one number is of another, or the percentage change between two values. Shows every step.',
    primaryKeyword: 'percentage calculator',
    relatedSlugs: [
      'compound-interest-calculator',
      'loan-calculator',
      'salary-calculator',
      'mortgage-calculator',
    ],
    icon: 'Percent',
    localProcessing: true,
    featured: true,
    componentKey: 'percentage-calculator',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'loan-calculator',
    name: 'Loan Calculator',
    shortName: 'Loan',
    category: 'calculators',
    title: 'Loan Calculator — Payment and Interest',
    description:
      'Calculate a fixed-rate loan payment, total interest and full amortisation schedule. Add an extra monthly payment to see how much sooner it clears.',
    primaryKeyword: 'loan calculator',
    relatedSlugs: [
      'mortgage-calculator',
      'compound-interest-calculator',
      'percentage-calculator',
      'salary-calculator',
    ],
    icon: 'Landmark',
    localProcessing: true,
    featured: true,
    componentKey: 'loan-calculator',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'mortgage-calculator',
    name: 'Mortgage Calculator',
    shortName: 'Mortgage',
    category: 'calculators',
    title: 'Mortgage Calculator — Payment Breakdown',
    description:
      'Estimate a monthly mortgage payment including property tax, insurance and HOA fees, with loan-to-value, total interest and a full amortisation table.',
    primaryKeyword: 'mortgage calculator',
    relatedSlugs: [
      'loan-calculator',
      'compound-interest-calculator',
      'percentage-calculator',
      'salary-calculator',
    ],
    icon: 'Home',
    localProcessing: true,
    featured: false,
    componentKey: 'mortgage-calculator',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'compound-interest-calculator',
    name: 'Compound Interest Calculator',
    shortName: 'Compound Interest',
    category: 'calculators',
    title: 'Compound Interest Calculator — Growth',
    description:
      'Project savings growth with any compounding frequency and regular contributions. Shows the yearly balance, total contributions and interest earned.',
    primaryKeyword: 'compound interest calculator',
    relatedSlugs: [
      'loan-calculator',
      'mortgage-calculator',
      'percentage-calculator',
      'salary-calculator',
    ],
    icon: 'TrendingUp',
    localProcessing: true,
    featured: false,
    componentKey: 'compound-interest-calculator',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'salary-calculator',
    name: 'Salary Calculator',
    shortName: 'Salary',
    category: 'calculators',
    title: 'Salary Calculator — Hourly to Annual',
    description:
      'Convert pay between hourly, daily, weekly, biweekly, semimonthly, monthly and annual rates using your own hours and paid weeks. Gross pay only.',
    primaryKeyword: 'salary calculator',
    relatedSlugs: [
      'percentage-calculator',
      'loan-calculator',
      'compound-interest-calculator',
      'date-difference-calculator',
    ],
    icon: 'Wallet',
    localProcessing: true,
    featured: true,
    componentKey: 'salary-calculator',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'age-calculator',
    name: 'Age Calculator',
    shortName: 'Age',
    category: 'calculators',
    title: 'Exact Age Calculator — Years, Months and Days',
    description:
      'Find an exact age in years, months and days from any birth date, plus total weeks and days lived, the day of the week born and the next birthday.',
    primaryKeyword: 'age calculator',
    relatedSlugs: ['date-difference-calculator', 'bmi-calculator', 'calorie-calculator'],
    icon: 'Cake',
    localProcessing: true,
    featured: true,
    componentKey: 'age-calculator',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'date-difference-calculator',
    name: 'Days Between Dates Calculator',
    shortName: 'Date Difference',
    category: 'calculators',
    title: 'Days Between Dates — Business Days Too',
    description:
      'Count the days, weeks, months and years between two dates, with options to include the end date or to count business days only.',
    primaryKeyword: 'days between dates',
    relatedSlugs: ['age-calculator', 'salary-calculator', 'loan-calculator'],
    icon: 'CalendarDays',
    localProcessing: true,
    featured: false,
    componentKey: 'date-difference-calculator',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'bmi-calculator',
    name: 'BMI Calculator',
    shortName: 'BMI',
    category: 'calculators',
    title: 'BMI Calculator — Metric and US Units',
    description:
      'Calculate body mass index in metric or US units, see the standard adult category and the healthy weight range for your height. Information only.',
    primaryKeyword: 'bmi calculator',
    relatedSlugs: ['calorie-calculator', 'age-calculator', 'percentage-calculator'],
    icon: 'Scale',
    localProcessing: true,
    featured: false,
    componentKey: 'bmi-calculator',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'calorie-calculator',
    name: 'Calorie Calculator',
    shortName: 'Calorie',
    category: 'calculators',
    title: 'Calorie Calculator — Daily TDEE Estimate',
    description:
      'Estimate resting metabolic rate and daily calorie needs with the Mifflin-St Jeor equation, plus illustrative targets for gradual loss or gain.',
    primaryKeyword: 'calorie calculator',
    relatedSlugs: ['bmi-calculator', 'age-calculator', 'percentage-calculator'],
    icon: 'Flame',
    localProcessing: true,
    featured: false,
    componentKey: 'calorie-calculator',
    updatedAt: '2026-09-16',
  },

  // --- Text & developer (10–15) --------------------------------------------
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    shortName: 'QR Code',
    category: 'text-developer-tools',
    title: 'Free QR Code Generator — PNG and SVG',
    description:
      'Create QR codes for links, text, email, phone, SMS and Wi-Fi networks. Download as PNG or SVG. Encoding happens in your browser, not on a server.',
    primaryKeyword: 'qr code generator',
    relatedSlugs: ['password-generator', 'uuid-generator', 'case-converter', 'character-counter'],
    icon: 'QrCode',
    localProcessing: true,
    featured: true,
    componentKey: 'qr-code-generator',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    shortName: 'Password',
    category: 'text-developer-tools',
    title: 'Secure Password Generator — 8–128 Characters',
    description:
      'Generate strong random passwords from 8 to 128 characters using your browser cryptographic random source. Nothing is stored, logged or transmitted.',
    primaryKeyword: 'password generator',
    relatedSlugs: ['uuid-generator', 'qr-code-generator', 'character-counter', 'case-converter'],
    icon: 'KeyRound',
    localProcessing: true,
    featured: true,
    componentKey: 'password-generator',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    shortName: 'UUID',
    category: 'text-developer-tools',
    title: 'Free UUID v4 Generator — Batch 100',
    description:
      'Generate up to 100 random version 4 UUIDs at once, with optional uppercase, braces or no hyphens. Copy them all or download them as a text file.',
    primaryKeyword: 'uuid generator',
    relatedSlugs: ['password-generator', 'qr-code-generator', 'case-converter', 'word-counter'],
    icon: 'Fingerprint',
    localProcessing: true,
    featured: false,
    componentKey: 'uuid-generator',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'word-counter',
    name: 'Word Counter',
    shortName: 'Word Counter',
    category: 'text-developer-tools',
    title: 'Word Counter — Reading Time and Keywords',
    description:
      'Count words, sentences and paragraphs as you type, with reading time, speaking time and the most frequent keywords in your text.',
    primaryKeyword: 'word counter',
    relatedSlugs: ['character-counter', 'case-converter', 'uuid-generator', 'qr-code-generator'],
    icon: 'AlignLeft',
    localProcessing: true,
    featured: true,
    componentKey: 'word-counter',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'character-counter',
    name: 'Character Counter',
    shortName: 'Character Counter',
    category: 'text-developer-tools',
    title: 'Character Counter — Unicode and UTF-8',
    description:
      'Count characters the way people see them and the way software measures them, with UTF-8 byte size, line counts and a character limit tracker.',
    primaryKeyword: 'character counter',
    relatedSlugs: ['word-counter', 'case-converter', 'password-generator', 'uuid-generator'],
    icon: 'Type',
    localProcessing: true,
    featured: false,
    componentKey: 'character-counter',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    shortName: 'Case Converter',
    category: 'text-developer-tools',
    title: 'Case Converter — 10 Text Formats',
    description:
      'Convert text to lowercase, UPPERCASE, Sentence case, Title Case, camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE or alternating case.',
    primaryKeyword: 'case converter',
    relatedSlugs: ['word-counter', 'character-counter', 'uuid-generator', 'qr-code-generator'],
    icon: 'CaseSensitive',
    localProcessing: true,
    featured: false,
    componentKey: 'case-converter',
    updatedAt: '2026-09-16',
  },

  // --- Images (16–22) ------------------------------------------------------
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    shortName: 'Image Compressor',
    category: 'image-tools',
    title: 'Image Compressor — JPG, PNG and WebP',
    description:
      'Compress JPG, PNG and WebP images in your browser. Adjust quality, cap dimensions and download one file or a ZIP. Nothing is uploaded to a server.',
    primaryKeyword: 'image compressor',
    relatedSlugs: [
      'jpg-compressor',
      'png-compressor',
      'image-resizer',
      'image-cropper',
      'image-to-pdf',
    ],
    icon: 'ImageDown',
    localProcessing: true,
    featured: true,
    componentKey: 'image-compressor',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'jpg-compressor',
    name: 'JPG Compressor',
    shortName: 'JPG Compressor',
    category: 'image-tools',
    title: 'JPG Compressor — Batch and No Upload',
    description:
      'Reduce JPG and JPEG file sizes with a quality slider and optional dimension cap. Batch several photos at once and download them as a ZIP.',
    primaryKeyword: 'jpg compressor',
    relatedSlugs: [
      'image-compressor',
      'png-compressor',
      'image-resizer',
      'jpg-to-png',
      'jpg-to-pdf',
    ],
    icon: 'FileImage',
    localProcessing: true,
    featured: false,
    componentKey: 'jpg-compressor',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'png-compressor',
    name: 'PNG Compressor',
    shortName: 'PNG Compressor',
    category: 'image-tools',
    title: 'PNG Compressor — Lossless or Smaller',
    description:
      'Shrink PNG files with a lossless pass that keeps every pixel, or a lossy mode that reduces colours for a much smaller file. Transparency is preserved.',
    primaryKeyword: 'png compressor',
    relatedSlugs: ['image-compressor', 'jpg-compressor', 'png-to-jpg', 'image-resizer'],
    icon: 'Images',
    localProcessing: true,
    featured: false,
    componentKey: 'png-compressor',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'image-resizer',
    name: 'Image Resizer',
    shortName: 'Image Resizer',
    category: 'image-tools',
    title: 'Image Resizer — Pixels, Percent and Presets',
    description:
      'Resize JPG, PNG and WebP images by pixels or percentage, with aspect-ratio lock, contain or cover fitting and a choice of output format.',
    primaryKeyword: 'image resizer',
    relatedSlugs: [
      'image-cropper',
      'image-compressor',
      'jpg-compressor',
      'png-compressor',
      'image-to-pdf',
    ],
    icon: 'Scaling',
    localProcessing: true,
    featured: false,
    componentKey: 'image-resizer',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'image-cropper',
    name: 'Image Cropper',
    shortName: 'Image Cropper',
    category: 'image-tools',
    title: 'Image Cropper — Rotate, Flip and Ratios',
    description:
      'Crop a photo freehand or to a fixed ratio, with zoom, rotate and flip. Keyboard and numeric controls included; the crop exports at full resolution.',
    primaryKeyword: 'image cropper',
    relatedSlugs: ['image-resizer', 'image-compressor', 'png-to-jpg', 'image-to-pdf'],
    icon: 'Crop',
    localProcessing: true,
    featured: false,
    componentKey: 'image-cropper',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'jpg-to-png',
    name: 'JPG to PNG Converter',
    shortName: 'JPG to PNG',
    category: 'image-tools',
    title: 'JPG to PNG Converter — Free and Private',
    description:
      'Convert JPG and JPEG photos to PNG in your browser, one at a time or in a batch, with correct orientation and a clear before-and-after size comparison.',
    primaryKeyword: 'jpg to png',
    relatedSlugs: ['png-to-jpg', 'image-compressor', 'jpg-compressor', 'image-resizer'],
    icon: 'ArrowLeftRight',
    localProcessing: true,
    featured: false,
    componentKey: 'jpg-to-png',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'png-to-jpg',
    name: 'PNG to JPG Converter',
    shortName: 'PNG to JPG',
    category: 'image-tools',
    title: 'PNG to JPG Converter — Pick a Background',
    description:
      'Convert PNG images to JPG with a quality slider and a choice of background colour for transparent areas. Batch conversion and ZIP download included.',
    primaryKeyword: 'png to jpg',
    relatedSlugs: ['jpg-to-png', 'png-compressor', 'image-compressor', 'image-resizer'],
    icon: 'ArrowRightLeft',
    localProcessing: true,
    featured: false,
    componentKey: 'png-to-jpg',
    updatedAt: '2026-09-16',
  },

  // --- PDF (23–28) ---------------------------------------------------------
  {
    slug: 'image-to-pdf',
    name: 'Image to PDF Converter',
    shortName: 'Image to PDF',
    category: 'pdf-tools',
    title: 'Image to PDF Converter — Reorder Pages',
    description:
      'Turn JPG, PNG and WebP images into a single PDF. Reorder pages, pick A4 or Letter, set margins and keep every aspect ratio intact.',
    primaryKeyword: 'image to pdf',
    relatedSlugs: ['jpg-to-pdf', 'pdf-merger', 'pdf-to-jpg', 'image-compressor', 'pdf-compressor'],
    icon: 'FilePlus2',
    localProcessing: true,
    featured: false,
    componentKey: 'image-to-pdf',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG Converter',
    shortName: 'PDF to JPG',
    category: 'pdf-tools',
    title: 'PDF to JPG Converter — Choose Pages',
    description:
      'Render any page of a PDF to a JPG image at your chosen resolution. Pick pages or ranges, preview thumbnails and download single files or a ZIP.',
    primaryKeyword: 'pdf to jpg',
    relatedSlugs: ['image-to-pdf', 'pdf-splitter', 'pdf-merger', 'jpg-compressor'],
    icon: 'FileImage',
    localProcessing: true,
    featured: false,
    componentKey: 'pdf-to-jpg',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF Converter',
    shortName: 'JPG to PDF',
    category: 'pdf-tools',
    title: 'JPG to PDF Converter — Reorder Photos',
    description:
      'Combine JPG photos into one PDF in the order you choose, with A4 or Letter pages, adjustable margins and automatic orientation correction.',
    primaryKeyword: 'jpg to pdf',
    relatedSlugs: ['image-to-pdf', 'pdf-merger', 'pdf-to-jpg', 'jpg-compressor'],
    icon: 'FileUp',
    localProcessing: true,
    featured: false,
    componentKey: 'jpg-to-pdf',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'pdf-compressor',
    name: 'PDF Compressor',
    shortName: 'PDF Compressor',
    category: 'pdf-tools',
    title: 'PDF Compressor — Two Compression Modes',
    description:
      'Make a PDF smaller in your browser. Optimise its structure without touching the pages, or rasterise them for a bigger saving, with the trade-offs spelled out.',
    primaryKeyword: 'pdf compressor',
    relatedSlugs: ['pdf-merger', 'pdf-splitter', 'image-compressor', 'pdf-to-jpg'],
    icon: 'FileArchive',
    localProcessing: true,
    featured: false,
    componentKey: 'pdf-compressor',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'pdf-merger',
    name: 'Merge PDF Files',
    shortName: 'PDF Merger',
    category: 'pdf-tools',
    title: 'Merge PDF Files — Private, No Upload',
    description:
      'Combine up to ten PDFs into one document in any order you like. Pages are copied, not re-rendered, so text stays selectable and page sizes stay exact.',
    primaryKeyword: 'merge pdf',
    relatedSlugs: ['pdf-splitter', 'image-to-pdf', 'pdf-compressor', 'pdf-to-jpg'],
    icon: 'Combine',
    localProcessing: true,
    featured: true,
    componentKey: 'pdf-merger',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'pdf-splitter',
    name: 'Split PDF Files',
    shortName: 'PDF Splitter',
    category: 'pdf-tools',
    title: 'Split PDF Files — Extract or Delete Pages',
    description:
      'Extract pages, split every page into its own file, cut a PDF into ranges or delete pages you do not need. Page sizes and rotation are preserved.',
    primaryKeyword: 'split pdf',
    relatedSlugs: ['pdf-merger', 'pdf-to-jpg', 'pdf-compressor', 'image-to-pdf'],
    icon: 'Split',
    localProcessing: true,
    featured: false,
    componentKey: 'pdf-splitter',
    updatedAt: '2026-09-16',
  },

  // --- Business (29–30) ----------------------------------------------------
  {
    slug: 'invoice-generator',
    name: 'Invoice Generator',
    shortName: 'Invoice',
    category: 'business-tools',
    title: 'Free Invoice Generator — PDF, No Signup',
    description:
      'Build a professional invoice with line items, discounts, tax and payment terms, then print it or download a PDF. No account, no data sent anywhere.',
    primaryKeyword: 'invoice generator',
    relatedSlugs: [
      'receipt-generator',
      'percentage-calculator',
      'image-to-pdf',
      'pdf-merger',
      'qr-code-generator',
    ],
    icon: 'FileSpreadsheet',
    localProcessing: true,
    featured: true,
    componentKey: 'invoice-generator',
    updatedAt: '2026-09-16',
  },
  {
    slug: 'receipt-generator',
    name: 'Receipt Generator',
    shortName: 'Receipt',
    category: 'business-tools',
    title: 'Receipt Generator — Print or PDF',
    description:
      'Create a clear receipt for a payment you have taken, with line items, tax, tip, amount tendered and change. Print it or save it as a PDF.',
    primaryKeyword: 'receipt generator',
    relatedSlugs: ['invoice-generator', 'percentage-calculator', 'image-to-pdf', 'pdf-compressor'],
    icon: 'Receipt',
    localProcessing: true,
    featured: false,
    componentKey: 'receipt-generator',
    updatedAt: '2026-09-16',
  },
] as const;

/** Number of tools contracted for launch (spec §2). */
export const EXPECTED_TOOL_COUNT = 30;
